VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 config.vm.box = "hashicorp/precise64"
 config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/site.yml"
 end
 config.vm.synced_folder ".", "/vagrant", disabled: true
 config.vm.network "forwarded_port", guest: 8080, host: 8080	
end